<?php

namespace App\Models;

use App\Casts\ExpiresAtCast;
use App\Lib\EShareTableType;
use App\Lib\Utils\RouteNameField;
use Exception;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Collection;

class ShareTable extends Model
{
    protected $fillable = [
        'member_id',
        'name',
        'description',
        'type',
        'expired_at',
        'short_code',
        'secret',
    ];

    protected $casts = [
        'expired_at' => ExpiresAtCast::class,
        'member_id' => 'int',
    ];

    use HasFactory;

    /**
     * @return \Illuminate\Database\Eloquent\Collection<VirtualFile> | VirtualFile[]
     */
    public function virtualFiles(): BelongsToMany
    {
        return $this->belongsToMany(VirtualFile::class, 'share_table_virtual_file', 'share_table_id', 'virtual_file_uuid', 'id', 'uuid');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Collection<VirtualFile> | VirtualFile[]
     */
    public function getAllVirtualFiles()
    {
        return $this->virtualFiles()->get();
    }

    public function shareTableVirtualFile(): HasMany
    {
        return $this->hasMany(ShareTableVirtualFile::class, 'share_table_id', 'id');
    }

    public function member(): HasOne
    {
        return $this->hasOne(Member::class, 'id', 'member_id');
    }

    //    public function __call($method, $parameters)
    //    {
    //        try {
    //            return parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    //        } catch (Exception $e) {
    //            dump($method, $parameters);
    //            if($method === "shareTablePermissions") {
    //                if(count($parameters) === 1 && $parameters[0] === null) {
    //                    dump('0');
    //                    return $this->internalShareTablePermissions()->rightJoin('share_tables', 'share_tables_id', '=', 'share_tables.id');
    //                } elseif (count($parameters) === 1) {
    //                    dump('1');
    //                    if($parameters[0] instanceof Member) {
    //                        return $this->internalShareTablePermissions()->where('member_id', '=', $parameters[0]->id);
    //                    }
    //                }
    //            }
    //        }
    //    }
    //
    //    private function internalShareTablePermissions(): \Illuminate\Database\Eloquent\Relations\MorphMany
    //    {
    //        return $this->morphMany(SharePermissions::class, 'permissible');
    //    }

    /**
     * @return Collection
     */
    public function relationMember()
    {
        $results = $this->shareTablePermission()->with('member')->getResults()->pluck('member');

        return $results;
    }

    public function shareTablePermission(): HasMany
    {
        return $this->hasMany(SharePermissions::class, 'share_tables_id', 'id');
    }

    public function shareURL(): string
    {
        return route(
            RouteNameField::PageShareableShareTableItem->value,
            ['shortcode' => $this->short_code],
        );
    }

    public function viewable(Member $member)
    {
        if ($this->type !== EShareTableType::public) {
            $memberPermission = $this->shareTablePermission()->where('member_id', '=', $member->id);
            if ($memberPermission->exists()) {
                $memberPermission = $memberPermission->getResults();
                dump($memberPermission);
            }
        }

        return true;
    }

    public function isOwner(?Member $member): bool
    {
        if ($member === null) {
            return false;
        }

        return $this->member_id === $member->id;
    }

    public function isPermissionMember(Member $member): bool
    {
        return $this->shareTablePermission()->where('member_id', '=', $member->id)->exists();
    }

    public function scopeViewableFor($query, ?Member $member)
    {
        if ($member === null) {
            return $query->where('type', EShareTableType::public->value);
        }

        return $query->where(function ($q) use ($member) {
            $q->where('type', EShareTableType::public->value)
                ->orWhere('member_id', $member->id)
                ->orWhereExists(function ($sub) use ($member) {
                    $sub->select(\DB::raw(1))
                        ->from('share_permissions')
                        ->whereColumn('share_permissions.share_tables_id', 'share_tables.id')
                        ->where('share_permissions.member_id', $member->id);
                });
        });
    }

    public function hasPassword(): bool
    {
        return $this->secret !== null && $this->secret !== '';
    }
}
